"""agrega tabla saldos_iniciales

Revision ID: a9bc2431b60c
Revises: b97d82d43381
Create Date: 2026-08-24 12:07:58.021988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bc2431b60c'
down_revision: Union[str, Sequence[str], None] = 'b97d82d43381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldos_iniciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('automotriz_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automotriz_id'], ['automotrices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'automotriz_id', name='uq_saldos_iniciales_fecha_automotriz')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos_iniciales')
    # ### end Alembic commands ###
