"""esquema inicial: 9 tablas

Revision ID: b97d82d43381
Revises: 
Create Date: 2026-08-24 11:40:53.896709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97d82d43381'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automotrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mes', 'anio', name='uq_periodos_mes_anio')
    )
    op.create_index('idx_periodos_fechas', 'periodos', ['fecha_inicio', 'fecha_fin'], unique=False)
    op.create_table('tipos_operacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['tipo_operacion_id'], ['tipos_operacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'partida_id', 'tipo_operacion_id', name='uq_sub_partidas_nombre_partida_tipo')
    )
    op.create_table('detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('sub_partida_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sub_partida_id'], ['sub_partidas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'sub_partida_id', name='uq_detalles_nombre_sub_partida')
    )
    op.create_table('planes_cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion_id', sa.Integer(), nullable=False),
    sa.Column('sub_partida_id', sa.Integer(), nullable=False),
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('automotriz_id', sa.Integer(), nullable=True),
    sa.Column('derechos', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automotriz_id'], ['automotrices.id'], ),
    sa.ForeignKeyConstraint(['detalle_id'], ['detalles.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['sub_partida_id'], ['sub_partidas.id'], ),
    sa.ForeignKeyConstraint(['tipo_operacion_id'], ['tipos_operacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('plan_cuenta_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=True),
    sa.Column('comprobante', sa.String(), nullable=True),
    sa.Column('ingresos', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('egresos', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('neto', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anulado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('movimiento_anulacion_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_adicional', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_anulacion_id'], ['movimientos.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.ForeignKeyConstraint(['plan_cuenta_id'], ['planes_cuentas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movimientos_fecha_anulado', 'movimientos', ['fecha', 'anulado'], unique=False)
    op.create_index('idx_movimientos_plan_cuenta_anulado', 'movimientos', ['plan_cuenta_id', 'anulado'], unique=False)
    op.create_index('idx_movimientos_usuario_creado', 'movimientos', ['usuario_id', 'creado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movimientos_usuario_creado', table_name='movimientos')
    op.drop_index('idx_movimientos_plan_cuenta_anulado', table_name='movimientos')
    op.drop_index('idx_movimientos_fecha_anulado', table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_table('planes_cuentas')
    op.drop_table('detalles')
    op.drop_table('sub_partidas')
    op.drop_table('usuarios')
    op.drop_table('tipos_operacion')
    op.drop_index('idx_periodos_fechas', table_name='periodos')
    op.drop_table('periodos')
    op.drop_table('partidas')
    op.drop_table('automotrices')
    # ### end Alembic commands ###
